[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = [
  "npm ci --prefer-offline --no-audit",
  "npx prisma generate"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx prisma migrate deploy && npm start"
